### ISSUE TITLE
Error invoking Method 'adminCheckAdmin': Internal server error [500]

### ISSUE THREAD

**Issue by hyperh** [sachinbhutani/flow-db-admin#10]
I'm logged in and when I try to access `localhost:3000/admin`, I get
`Error invoking Method 'adminCheckAdmin': Internal server error [500]`
in the console. And the admin page says `You need to be an admin to view this page`, even though I'm signed into an admin account already.

Server logs
```
I20151104-13:25:28.747(8)? Exception while invoking method 'adminCheckAdmin' ReferenceError: Match is not defined
I20151104-13:25:28.748(8)?     at [object Object].Meteor.methods.adminCheckAdmin (packages/sach_flow-db-admin/lib/server/methods.coffee:76:21)
I20151104-13:25:28.749(8)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151104-13:25:28.749(8)?     at livedata_server.js:708:19
I20151104-13:25:28.749(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151104-13:25:28.749(8)?     at livedata_server.js:706:40
I20151104-13:25:28.749(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151104-13:25:28.749(8)?     at livedata_server.js:704:46
I20151104-13:25:28.750(8)?     at tryCallTwo (/Users/hl/.meteor/packages/promise/.0.5.1.1vhv18x++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151104-13:25:28.750(8)?     at doResolve (/Users/hl/.meteor/packages/promise/.0.5.1.1vhv18x++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151104-13:25:28.750(8)?     at new Promise (/Users/hl/.meteor/packages/promise/.0.5.1.1vhv18x++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
```

**Comment by hyperh** [comment]
A quick work around for me was to download the zip and move the code into my own `/packages` directory. I removed all the checks from `methods.coffee` and `publish.coffee`. I can see to CRUD for my collections. Users and roles still seems to be a bit finicky though.

**Comment by BeSports** [comment]
Getting the same error, would love to see this fixed! Makes the package unusable for me.

**Comment by markoshust** [comment]
`meteor add check`

**Comment by sachinbhutani** [comment]
thanks @markoshust

**Comment by derwaldgeist** [comment]
I'm getting the same error and are still on Meteor 1.1. Any chance to downport the fix to this Meteor version?

**Comment by marktomm** [comment]
Still having the same issue, but only in production (meteor run --production).

**Comment by marktomm** [comment]
I had the same issue.

When a user is created in my app, 'regularUser' role is appended to him. This package didn't change it and i got this error. After manually changing to 'admin' in mongo everything started working fine
