### ISSUE TITLE
autoform options don't work

### ISSUE THREAD

**Issue by markoshust** [sachinbhutani/flow-db-admin#12]
I have a schema like so:

```
lesson.attachSchema(new SimpleSchema({
  name: {
    type: String,
    label: "Name"
  },
  description: {
    type: String,
    label: "Description"
  },
  rank: {
    type: Number,
    label: "Rank"
  },
  phase_id: {
    type: String,
    regEx: SimpleSchema.RegEx.Id,
    label: "Phase ID",
    index: 1,
    autoform: {
      options: function() {
        _.map(phase.find().fetch(), function(phase) {
          return {
            label: phase.name,
            value: phase._id
          }
        });
      }
    }
  },
...
```

Note the phase_id > autoform > options definition. I'd like to pull in the phases, and map an id and name to the phase_id field. This isn't working.

**Comment by markoshust** [comment]
This could be because there is no code for this :laughing: 

https://github.com/sachinbhutani/flow-db-admin/search?utf8=%E2%9C%93&q=options

Is this supposed to be automatically handled by autoform?

**Comment by sachinbhutani** [comment]
That's the idea! 
Update to autoform version 5.7.1  - might help. 
Please let me know.

**Comment by markoshust** [comment]
No dice -- here's how it shows:

![screen shot 2015-11-07 at 7 38 30 am](https://cloud.githubusercontent.com/assets/437029/11015194/97eefa68-8522-11e5-87dc-dc64cfc79be9.png)

I'm assuming "Phase ID" should show as a select dropdown menu with the options of id:name of phases?

**Comment by markoshust** [comment]
Ok, so I just submitted a PR to fix the documentation. The `autoform.options` object should be a function.... that returns something ;) The original `yogiben:admin` documentation was missing this.

Onto the second issue. If I setup my new `phase_id` object like this:

```
phase_id: {
    type: String,
    regEx: SimpleSchema.RegEx.Id,
    label: "Phase ID",
    index: 1,
    autoform: {
      options: function() {
        return _.map([
          {_id: 1, name: "Phase 1"},
          {_id: 2, name: "Phase 2"}
        ], function(phase) {
          return {
            label: phase.name,
            value: phase._id
          }
        });
      }
    }
  }
```

I know get a select dropdown with options. However, if I change it to the cursor fetch:

```
phase_id: {
    type: String,
    regEx: SimpleSchema.RegEx.Id,
    label: "Phase ID",
    index: 1,
    autoform: {
      options: function() {
        return _.map(phase.find().fetch(), function(phase) {
          return {
            label: phase.name,
            value: phase._id
          }
        });
      }
    }
  }
```

I get a select menu, but without any options. If I turn on `autopublish`, I get the options with phase names/vals (yay, at least that works now :+1: )

I would assume adding autoform options would auto-subscribe to these requests, but this doesn't happen, so we have three choices: autosubscribe to these requests, make another object where we can define publications to subscribe to, or have a manual subscribe process. I think option 1 or 2 would be better, as it would make things a lot easier for the end-user.

**Comment by markoshust** [comment]
Here is the suggested way to do this with `yogiben:admin`: https://github.com/yogiben/meteor-admin/#custom-route-options

This was ported to Flow Router, but I'm assuming this feature wasn't setup. 

This would make `AdminConfig.collections.lesson` use something like:

```
lesson: {
      tableColumns: [
        { label: 'Name', name: 'name' },
        { label: 'Description', name: 'description' },
        { label: 'Rank', name: 'rank' },
        { label: 'Phase ID', name: 'phase_id' }
      ],
      routes: {
        new: {
          waitOn: function () { return Meteor.subscribe('lesson') && Meteor.subscribe('phase'); }
        },
        view: {
          waitOn: function () { return Meteor.subscribe('lesson') && Meteor.subscribe('phase'); }
        },
        edit: {
          waitOn: function () { return Meteor.subscribe('lesson') && Meteor.subscribe('phase'); }
        }
      }
    }
```

However, this doesn't follow DRY principle. Since the collection is automatically subscribed to, something like this would be more ideal:

```
lesson: {
      tableColumns: [
        { label: 'Name', name: 'name' },
        { label: 'Description', name: 'description' },
        { label: 'Rank', name: 'rank' },
        { label: 'Phase ID', name: 'phase_id' }
      ],
      depSubs: [
        { name: 'phase', params: {}}
      ]
    }
```

The idea being `depSubs` > `params` will define the optional/additional parameters passed into the sub, in the situation where you need to filter the additional subscription data.

In the interim, something like this would also work and is simpler:

```
lesson: {
      tableColumns: [
        { label: 'Name', name: 'name' },
        { label: 'Description', name: 'description' },
        { label: 'Rank', name: 'rank' },
        { label: 'Phase ID', name: 'phase_id' }
      ],
      depSubs: ['phase']
    }
```

**Comment by otech-nl** [comment]
This is an old issue, but for future reference: 

I got this to work by adding a 'extraSubscriptions' option to the column definition and than add:

    Template.fAdminLayout.rendered = () => {
        var collectionName = FlowRouter.getParam('collectionName');
        var collectionConfig = AdminConfig.collections[collectionName];
        if( 'extraSubscriptions' in collectionConfig) {
            collectionConfig.extraSubscriptions.forEach((sub) => {
                Meteor.subscribe(sub);
            });
        }
    };
