### ISSUE TITLE
Question about CSS frameworks

### ISSUE THREAD

**Issue by chhudson** [sachinbhutani/flow-db-admin#14]
My current project is using the semantic ui framework. My question is will adding the bootstrap framework throw things off or is there a way to isolate bootstrap to only work with this Admin? Is this even possible?

**Comment by sachinbhutani** [comment]
there's no way to isolate as of now, 
I have used semantic for my site with bootstrap for the admin - a few elements behave weird in the admin-lte theme, but it's still usable.
