### ISSUE TITLE
Custom edit template not working

### ISSUE THREAD

**Issue by farshid1** [sachinbhutani/flow-db-admin#16]
I'm following the instruction in order to have a custom template for my edit page. Part of my AdminConfig is as follow:

    News:
      tableColumns: [
        {label: 'ID', name: '_id'}
        {label: 'Title', name: 'title'}
      ]
      templates:
        new:
          name: 'newNews'
        edit:
          name: 'editNews'
          data:
            news: Meteor.isClient && Session.get('admin_doc')

and here's my `editNews` template:

    +autoForm collection="News" type="update" doc=news id="news-update"
        +afQuickField(name ="title")
        +afQuickField(name ="content")
        +afQuickField(name ="image")
        button(type="submit", class="btn btn-primary") Update

First of all, using `doc=news` does not prepopulate my form. I had to find a work around and use a helper function to get the doc. In addition, when user clicks the delete button in the list of documents, the alert component in the edit page is not displayed.

**Comment by CaptainN** [comment]
Better late than never? You can use a template helper to grab that data instead of passing it along in the data object:

```JavaScript
Template.GridEdit.helpers ({
  news_doc () {
    return Session.get('admin_doc')
  },
  collection () {
    return News
  },
})
```

```{{> quickForm id="admin_update" collection=collection doc=news_doc buttonContent='Update'}}```

**Comment by farshid1** [comment]
Thanks for the response. Haven't worked with meteor this year.
