### ISSUE TITLE
collection2-core, autoform6 and simpl-schema support

### ISSUE THREAD

**Issue by jankapunkt** [sachinbhutani/flow-db-admin#33]
As of 2017 there have been several changes to depending packages of this one.

collection2 is now deprecated and replaced by collection2-core
laded:simple-schema is deprecated and replaced by a npm package (simpl-schema)
autoform is major version 6

If recent apps want to use this package, it is crucial to provide this update.

Note: I will create a PR, when I made transition complete.

**Comment by sachinbhutani** [comment]
thanks, Merged

**Comment by HamzaDevz** [comment]
Hi, when i add the version 1.2.0 with `meteor add sach:flow-db-admin@1.2.0` i have the error: no such version sach:flow-db-admin@1.2.0

How can i found this version ?
