### ISSUE TITLE
Error visualizing users database

### ISSUE THREAD

**Issue by tcastelli** [sachinbhutani/flow-db-admin#4]
Hello, I've just tried this in order to have and admin panel for 1.2 and everything seems to be working besides the view of Meteor.users collection. This is what I get(i get the correct number of users in the dashboard but then...)

````javascript
Error: value is undefined
AdminTables.Users<.columns<.render@http://localhost:8080/packages/sach_flow-db-admin.js?ed89fd8442b134f468ab64c0c8aafb9693650eb8:469:9
_fnGetObjectDataFn/<@http://localhost:8080/packages/aldeed_tabular.js?402599831726fb93f98209c4ae93cf5b40a63e89:1332:12
_fnColumnOptions/oCol.fnGetData@http://localhost:8080/packages/aldeed_tabular.js?402599831726fb93f98209c4ae93cf5b40a63e89:818:5
_fnGetCellData@http://localhost:8080/packages/aldeed_tabular.js?402599831726fb93f98209c4ae93cf5b40a63e89:1225:24
_fnColumnTypes@http://localhost:8080/packages/aldeed_tabular.js?402599831726fb93f98209c4ae93cf5b40a63e89:990:1
_fnSort@http://localhost:8080/packages/aldeed_tabular.js?402599831726fb93f98209c4ae93cf5b40a63e89:4666:3
_fnReDraw@http://localhost:8080/packages/aldeed_tabular.js?402599831726fb93f98209c4ae93cf5b40a63e89:2220:4
_fnSortListener@http://localhost:8080/packages/aldeed_tabular.js?402599831726fb93f98209c4ae93cf5b40a63e89:4896:3
_fnSortAttachListener/<@http://localhost:80[…]
````

My users schema is quite complex with different autoform plugins, but i have tried to simplify and use another simpleschema

````javascript
userSchema: new SimpleSchema({
        username: {
            type: String            
        }
    })
````

but even by using that mode i get the same error as before

**Comment by sachinbhutani** [comment]
Not sure what's causing this as the error is inside the tabular package, but it most likely is not finding value for one of the following 
- user's email 
- user's name, 
- admin role on the user
- user creation date.
can you try using a simple custom template with User collection as mentioned in the 'Custom Template' section of the documentation ?

**Comment by tcastelli** [comment]
thanks!, after doing many tests, i've figured out that I have some users that are created without a mail(they have a name but the mail can be set after they log in for the first time), any idea on how to change it to work with this kind of users?

**Comment by sachinbhutani** [comment]
I can do a quick patch for it. 
try the change in this PR
https://github.com/sachinbhutani/flow-db-admin/pull/5

**Comment by tcastelli** [comment]
That PR is not enough, after playing arround, changing this in startup.cofee makes it work
````javascript
 {
      data: 'emails'
      title: 'Email'
      render: (value) ->
        if value then value[0].address else ''
      searchable: true
    }
   {
			data: 'emails'
			title: 'Mail'
			# TODO: use `tmpl`
			createdCell: (node, cellData, rowData) ->
				if cellData
					return $(node).html(Blaze.toHTMLWithData(Template.adminUsersMailBtn, { emails: cellData }, node))
				return
			width: '40px'
		}
````
If you cand add it to the PR it will be helpful! :)
