### ISSUE TITLE
Breadcrumbs wrong for users

### ISSUE THREAD

**Issue by mbeynon** [sachinbhutani/flow-db-admin#6]
The left menu correctly uses the route to view the list of users as "/admin/view/Users".  In contrast, the breadcrumbs view at the top of the pane shows "/admin/Users" that doesn't have a route and produces the following error in the client js console:

There is no route for the path: /admin/Users/Router._notfoundRoute @ router.js:347(anonymous function) @ router.js:5352.Route.middleware @ client.browserify.js:566nextEnter @ client.browserify.js:3982.Route.middleware @ client.browserify.js:567nextEnter @ client.browserify.js:3982.Route.middleware @ client.browserify.js:567nextEnter @ client.browserify.js:3982.Route.middleware @ client.browserify.js:567nextEnter @ client.browserify.js:3982.Route.middleware @ client.browserify.js:567nextEnter @ client.browserify.js:398nextExit @ client.browserify.js:3862.Route.middleware @ client.browserify.js:567nextExit @ client.browserify.js:3872.Route.middleware @ client.browserify.js:567nextExit @ client.browserify.js:387Triggers.runTriggers @ triggers.js:89Router.route.route._exitHandle @ router.js:1162.Route.middleware @ client.browserify.js:566nextExit @ client.browserify.js:3872.Route.middleware @ client.browserify.js:567nextExit @ client.browserify.js:3872.page.dispatch @ client.browserify.js:4022.page.show @ client.browserify.js:293Router.initialize._.each.self._page.(anonymous function) @ router.js:382onclick @ client.browserify.js:693

**Comment by sachinbhutani** [comment]
thanks, 
That was miss, fixed now. will update new version with other fix on roles.
