### ISSUE TITLE
Removing roles for a user fails

### ISSUE THREAD

**Issue by mbeynon** [sachinbhutani/flow-db-admin#7]
I created an empty meteor project just to test this.  Have a fixture that creates "admin" and "editor" roles, a dedicated admin@test.com account for driving the /admin UI, and several dummy accounts with no roles.  I then used the /admin view to add the "admin" and "editor" roles, which works just fine and creates the following user record.

{
    "_id" : "5fm3DnEv7fPuK7MSv",
    "createdAt" : ISODate("2015-10-18T03:06:36.793Z"),
    "services" : {
        "password" : {
            "bcrypt" : "$2a$10$7N96hW7wnJdDPMdeDM2Xo..pJ.5/IqgI6wUDC11SPhAH598SB65U2"
        }
    },
    "username" : "14xcUjsPIH@test.com",
    "emails" : [ 
        {
            "address" : "14xcUjsPIH@test.com",
            "verified" : false
        }
    ],
    "roles" : {
        "__global_roles__" : [ 
            "editor", 
            "admin"
        ]
    }
}

In contrast, trying to remove the role just added results in a failure.  Note this happens for both the admin role and other roles I created for testing.  The following is output the browser js console:

There is no route for the path: /admin/Users/Router._notfoundRoute @ router.js:347(anonymous function) @ router.js:5352.Route.middleware @ client.browserify.js:566nextEnter @ client.browserify.js:3982.Route.middleware @ client.browserify.js:567nextEnter @ client.browserify.js:3982.Route.middleware @ client.browserify.js:567nextEnter @ client.browserify.js:3982.Route.middleware @ client.browserify.js:567nextEnter @ client.browserify.js:3982.Route.middleware @ client.browserify.js:567nextEnter @ client.browserify.js:398nextExit @ client.browserify.js:3862.Route.middleware @ client.browserify.js:567nextExit @ client.browserify.js:3872.Route.middleware @ client.browserify.js:567nextExit @ client.browserify.js:387Triggers.runTriggers @ triggers.js:89Router.route.route._exitHandle @ router.js:1162.Route.middleware @ client.browserify.js:566nextExit @ client.browserify.js:3872.Route.middleware @ client.browserify.js:567nextExit @ client.browserify.js:3872.page.dispatch @ client.browserify.js:4022.page.show @ client.browserify.js:293Router.initialize._.each.self._page.(anonymous function) @ router.js:382onclick @ client.browserify.js:693
events.coffee:16 removing user
meteor.js:862 Error invoking Method 'adminRemoveUserToRole': Internal server error [500]

And the following exception in the server console:

I20151017-23:19:28.841(-4)? Exception while invoking method 'adminRemoveUserToRole' Error: Roles error: Can't mix grouped and non-grouped roles for same user
I20151017-23:19:28.841(-4)?     at Object._.extend.removeUsersFromRoles (packages/alanning_roles/roles_common.js:247:1)
I20151017-23:19:28.842(-4)?     at [object Object].Meteor.methods.adminRemoveUserToRole (packages/sach_flow-db-admin/lib/server/methods.coffee:102:10)
I20151017-23:19:28.842(-4)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
I20151017-23:19:28.842(-4)?     at livedata_server.js:708:19
I20151017-23:19:28.842(-4)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20151017-23:19:28.842(-4)?     at livedata_server.js:706:40
I20151017-23:19:28.842(-4)?     at [object Object]._.extend.withValue (packages/meteor/packages/meteor.js:1013:1)
I20151017-23:19:28.842(-4)?     at livedata_server.js:704:46
I20151017-23:19:28.842(-4)?     at tryCallTwo (/Users/beynon/.meteor/packages/promise/.0.5.0.15f7kag++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151017-23:19:28.842(-4)?     at doResolve (/Users/beynon/.meteor/packages/promise/.0.5.0.15f7kag++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)

**Comment by sachinbhutani** [comment]
fixed with version 1.1.4.

**Comment by sachinbhutani** [comment]
thanks for testing in detail.
