### ISSUE TITLE
Meteor.users collection not working as expected in admin

### ISSUE THREAD

**Issue by abhirakshit** [sachinbhutani/flow-db-admin#9]
I am having some weird issues while using the Meteor.users collection. All other collections are working as expected. 
I have made a separate package for my user related functionality which contains the user schema and the adminConfig file is in another package which depends on the user package.

a) In the adminConfig object if I put the "userSchema = null" as mentioned in the docs I get a "TypeError: Cannot read property 'showEditColumn' of null" error
b) If a put a new simpleSchema() for the userSchema I get a "Error: userSchema is not in the [object global]" error
c) If I don't put any user related info in the adminConfig but do add a schema somewhere in the code the users table is populated correctly. The add and delete also works fine but when I try to view/edit the the user the autoform although shows up with the correct schema I added but with no data populated. I am able to update the form by adding some data to the blank fields and they get saved correctly but I am not able to update the roles for the user. It does not throw any error on the server or in the browser console.

Is there something more I need to do for the Meteor.users to function which is not currently documented in the readme section?

**Comment by sachinbhutani** [comment]
for option c) - do you have the roles in the default GLOBAL group or any specific group ? 
I will try to look into it the c option. 
a) b) might be broken due to some other changes.

**Comment by abhirakshit** [comment]
I have not defined any groups for my roles in the application. Everything is in the default GLOBAL group. 

I also have a few collections which depend on other collections for their inputs. Is there a way to subscribe to individual subscriptions like the meteor admin from yogiben

```javascript
AdminConfig = {
  // ...
  collections: {
    Posts: {
      routes: {
        new: {
          waitOn: function () { return Meteor.subscribe('images'); }
        },
        view: {
          waitOn: function () { return Meteor.subscribe('images'); }
        },
        edit: {
          waitOn: function () { return Meteor.subscribe('images'); }
        }
      }
    }
  }
}
```

**Comment by abhirakshit** [comment]
Sorry closed by mistake.

**Comment by abhirakshit** [comment]
I was using the groups incorrectly causing the issue. It works now.
